# Conda env config
# ----------------

# To create:
#   $ conda env create -f environment.yml

# To activate:
#   $ conda activate eotopia-processing

# To update:
#   $ conda env update -f environment.yml

# To remove:
#   $ conda remove --name eotopia --all -y

---

name: eotopia


channels:
    - defaults

dependencies:

    # conda dependencies
    # Use single '=' signs!

    - python=3.7
    - pip=20.2.2
    - libspatialindex
    - matplotlib=3.0.3

    - pip:

          # pip requirements
          # Use double '==' signs!
          - sentinelhub==3.2.1
          - geopandas==0.8.1
          - fs==2.4.9
          - numpy>=1.19.0
          - attrs>=20.3.0
          - hypothesis==6.12.0
          - tqdm>=4.50.2
          
