# Conda env config
# ----------------

# To create:
#   $ conda env create -f environment.yml

# To activate:
#   $ conda activate eotopia-processing

# To update:
#   $ conda env update -f environment.yml

# To remove:
#   $ conda remove --name eotopia --all -y

---

name: eotopia


channels:
    - defaults

dependencies:

    # conda dependencies
    # Use single '=' signs!

    - python=3.7
    - pip=20.2.2
    - libspatialindex
    - matplotlib=3.0.3

    - pip:

          # pip requirements
          # Use double '==' signs!
          - lxml>=4.6.1
          - sentinelhub==3.2.1
          - rasterio==1.1.8
          - geopandas==0.8.1
          - numpy>=1.19.0
          - eo-learn-core==0.9.1
